#!/bin/bash

checkpoint_name="$1$(date +%s).tar.gz"
sudo podman container checkpoint --export $checkpoint_name $2
sudo scp -i "$3" $4/$(checkpoint_name) ubuntu@$5:$4 && return $checkpoint_name
return 1
